- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes
- name: Install Git
  apt:
    name: git
  become: yes
- name: Get www Repo
  shell: |
    cd /tmp;
    git clone https://github.com/ltimossi92/www.git;
    sudo cp ./www/www/index.nginx-debian.html /var/www/html/
- name: Start Nginx Service
  service:
    name: nginx
    state: started
  become: yes